apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: umiszf98m-go 
  janus-idp.io/tekton: umiszf98m-go
  backstage.io/kubernetes-id: umiszf98m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: umiszf98m-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml